# Site
name: "Munkyeong"
title: "Munkyeong"
description: "Welcome to Munkyeong-blog."
logo: "assets/images/logo.png"
favicon: "assets/images/logo.png"
baseurl: /home
google_analytics: "UA-46278016-1"
disqus: "demowebsite"
mailchimp-list: "https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  munkyeong:
    name: munkeyong
    display_name: munkyeong
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: horse6953@naver.com
    web: https://blog.naver.com/horse6953
    instargram: https://www.instagram.com/mooo_nk/
    description: "Pusan ​​National University CSE student. Responsible for computer-related postings or projects."
  kangoll:
    name: kangoll
    display_name: kangoll
    avatar: "assets/images/avatar.png"
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: horse6953@gmail.com
    web: https://blog.naver.com/horse6953
    instargram: https://www.instagram.com/gong_jae_il
    description: "23 year old college student.I like drawing and traveling."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, vendor]
